INSERT INTO FILM_ZANR VALUES (4, 'TEST');
INSERT INTO FILM_ZANR VALUES (30, 'TEST');
INSERT INTO FILM_ZANR VALUES (1, 'KOM');
commit;

 -- DELETE FROM FILM_ZANR WHERE ID_FILMU = 1 AND ZANR_KOD = 'KOM';